export {default as Dashboard} from './Dashboard';
export {default as About} from './About';
export {default as Login} from './Login';
export {default as AdminLogin} from './AdminLogin';
export {default as AdminSignup} from './AdminSignup';
export {default as Signup} from './Signup';
export {default as ForgotPassword} from './ForgotPassword';
export {default as ManageUsers} from './ManageUsers';
export {default as ManageAdmins} from './ManageAdmins';
export {default as Branch } from './branch';
export {default as AddBranch } from './AddBranch';
export {default as ManageVehicle } from './ManageVehicle';
export {default as AddVehicle } from './AddVehicle';
export {default as NotFound } from './NotFound';