export {default as Dashboard} from './Dashboard';
export {default as About} from './About';
export {default as Login} from './Login';
export {default as AdminLogin} from './AdminLogin';
export {default as AdminSignup} from './AdminSignup';
export {default as Signup} from './Signup';
export {default as ForgotPassword} from './ForgotPassword';
export {default as ManageUsers} from './ManageUsers';
export {default as ManageAdmins} from './ManageAdmins';